databases:
  - name: poll_plus_plus
    databaseName: poll_plus_plus_prod
    user: poll_plus_plus_user

services:
  - type: web
    name: poll_plus_plus
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poll_plus_plus
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
